name: Fetch strace (ARM64 Static)

on:
  workflow_dispatch:

jobs:
  fetch:
    name: Fetch strace (ARM64)
    runs-on: ubuntu-latest

    steps:
      - name: Download strace from Alpine
        run: |
          wget https://dl-cdn.alpinelinux.org/alpine/edge/main/aarch64/strace-6.19-r0.apk
          tar xzf strace-6.19-r0.apk
          file usr/bin/strace | grep 'statically linked'
          mv usr/bin/strace ./strace-static-arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: strace-static-arm64
          path: ./strace-static-arm64
          retention-days: 90
